# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charity_name', models.CharField(max_length=100)),
                ('charity_country', models.CharField(max_length=100)),
                ('charity_logo', models.CharField(max_length=1000)),
                ('charity_description', models.CharField(max_length=5000)),
            ],
        ),
    ]
