# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DEFAULT', max_length=100)),
                ('type', models.CharField(choices=[('', 'Default'), ('G', 'General Charitable Purposes'), ('E', 'Education/Training'), ('H', 'Advancement of Health/Saving Lives'), ('D', 'Disability'), ('P', 'Prevention or Relief of Poverty'), ('O', 'Overseas Aid/Famine Relief'), ('H', 'Accommodation/Housing'), ('R', 'Religious Activities'), ('C', 'Arts/Culture/Heritage/Science'), ('S', 'Amateur Sport'), ('AN', 'Animals'), ('EN', 'Environment'), ('EC', 'Economic/Community Development/Employment'), ('A', 'Armed Forces'), ('HR', 'Human Rights/Equality'), ('RE', 'Recreation'), ('OT', 'Other')], max_length=2)),
                ('register_id', models.IntegerField(default=0, unique=True)),
                ('area_served', models.CharField(default='DEFAULT', max_length=100)),
                ('total_income', models.IntegerField(default=0)),
                ('target', models.CharField(choices=[('', 'Default'), ('C', 'Children/Young People'), ('E', 'Elderly/Old People'), ('D', 'People with disabilities'), ('R', 'People of particular ethnic/racial origin'), ('P', 'The general public'), ('O', 'Other')], max_length=1)),
                ('logo', models.CharField(default='DEFAULT', max_length=1000)),
                ('description', models.TextField()),
                ('paypal', models.CharField(default='DEFAULT', max_length=100)),
            ],
        ),
    ]
