# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('url', models.CharField(default='DEFAULT', max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='charity',
            name='type',
            field=models.CharField(choices=[('', 'Default'), ('G', 'General Charitable Purposes'), ('E', 'Education/Training'), ('H', 'Advancement of Health/Saving Lives'), ('D', 'Disability'), ('P', 'Prevention or Relief of Poverty'), ('O', 'Overseas Aid/Famine Relief'), ('R', 'Religious Activities'), ('C', 'Arts/Culture/Heritage/Science'), ('S', 'Amateur Sport'), ('AN', 'Animals'), ('EN', 'Environment'), ('EC', 'Economic/Community Development/Employment'), ('A', 'Armed Forces'), ('HR', 'Human Rights/Equality'), ('RE', 'Recreation'), ('AH', 'Accommodation/Housing'), ('OT', 'Other')], max_length=2),
        ),
        migrations.AddField(
            model_name='volunteering',
            name='charity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity.Charity'),
        ),
    ]
