# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charity',
            name='charity_country',
        ),
        migrations.AddField(
            model_name='charity',
            name='charity_area_served',
            field=models.CharField(default='DEFAULT', max_length=100),
        ),
        migrations.AddField(
            model_name='charity',
            name='charity_register_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charity',
            name='charity_target',
            field=models.CharField(default='DEFAULT', max_length=100),
        ),
        migrations.AddField(
            model_name='charity',
            name='charity_total_income',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charity',
            name='charity_type',
            field=models.CharField(default='DEFAULT', max_length=50),
        ),
        migrations.AlterField(
            model_name='charity',
            name='charity_description',
            field=models.CharField(default='DEFAULT', max_length=5000),
        ),
        migrations.AlterField(
            model_name='charity',
            name='charity_logo',
            field=models.CharField(default='DEFAULT', max_length=1000),
        ),
        migrations.AlterField(
            model_name='charity',
            name='charity_name',
            field=models.CharField(default='DEFAULT', max_length=100),
        ),
    ]
