# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_auto_20161129_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteering',
            name='start_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
