# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_auto_20161015_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charity',
            old_name='charity_area_served',
            new_name='area_served',
        ),
        migrations.RenameField(
            model_name='charity',
            old_name='charity_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='charity',
            old_name='charity_logo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='charity',
            old_name='charity_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='charity',
            old_name='charity_register_id',
            new_name='register_id',
        ),
        migrations.RenameField(
            model_name='charity',
            old_name='charity_target',
            new_name='target',
        ),
        migrations.RenameField(
            model_name='charity',
            old_name='charity_total_income',
            new_name='total_income',
        ),
        migrations.RenameField(
            model_name='charity',
            old_name='charity_type',
            new_name='type',
        ),
    ]
