# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-30 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_auto_20161113_1725'),
        ('charity', '0002_auto_20161129_2021'),
    ]

    operations = [
    ]
