# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0003_auto_20161019_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='paypal',
            field=models.CharField(default='DEFAULT', max_length=100),
        ),
    ]
