# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0004_auto_20161130_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteering',
            name='name',
            field=models.CharField(default='DEFAULT', max_length=200),
        ),
    ]
