# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0004_charity_paypal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='charity',
            name='register_id',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='charity',
            name='target',
            field=models.CharField(choices=[('', 'Default'), ('C', 'Children/Young People'), ('E', 'Elderly/Old People'), ('D', 'People with disabilities'), ('R', 'People of particular ethnic/racial origin'), ('P', 'The general public'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='charity',
            name='type',
            field=models.CharField(choices=[('', 'Default'), ('G', 'General Charitable Purposes'), ('E', 'Education/Training'), ('H', 'Advancement of Health/Saving Lives'), ('D', 'Disability'), ('P', 'Prevention or Relief of Poverty'), ('O', 'Overseas Aid/Famine Relief'), ('H', 'Accommodation/Housing'), ('R', 'Religious Activities'), ('C', 'Arts/Culture/Heritage/Science'), ('S', 'Amateur Sport'), ('AN', 'Animals'), ('EN', 'Environment'), ('EC', 'Economic/Community Development/Employment'), ('A', 'Armed Forces'), ('HR', 'Human Rights/Equality'), ('RE', 'Recreation'), ('OT', 'Other')], max_length=2),
        ),
    ]
