# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_auto_20161113_1725'),
        ('charity', '0005_volunteering_name'),
    ]

    operations = [
    ]
