# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-02 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0005_auto_20161230_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charity',
            name='donations',
        ),
    ]
