# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-28 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0006_merge_20161201_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='type',
            field=models.CharField(choices=[('', 'Default'), ('G', 'General Charitable Purposes'), ('E', 'Education/Training'), ('H', 'Advancement of Health/Saving Lives'), ('D', 'Disability'), ('P', 'Prevention or Relief of Poverty'), ('O', 'Overseas Aid/Famine Relief'), ('R', 'Religious Activities'), ('C', 'Arts/Culture/Heritage/Science'), ('S', 'Amateur Sport'), ('AN', 'Animals'), ('EN', 'Environment'), ('EC', 'Economic/Community Development/Employment'), ('A', 'Armed Forces'), ('HR', 'Human Rights/Equality'), ('RE', 'Recreation'), ('AH', 'Accommodation/Housing'), ('OT', 'Other')], max_length=2),
        ),
    ]
