# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-02 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0006_remove_charity_donations'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='donations',
            field=models.IntegerField(default=0),
        ),
    ]
