# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-30 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0006_auto_20161227_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='logo',
            field=models.CharField(default='DEFAULT', max_length=1000),
        ),
    ]
