# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-29 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0007_auto_20161228_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='paypal',
            field=models.CharField(default='DEFAULT', max_length=100, unique=True),
        ),
    ]
