# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-03 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0007_charity_donations'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='admin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charity',
            name='charitableActivity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charity',
            name='fundraising',
            field=models.IntegerField(default=0),
        ),
    ]
