# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-30 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0008_auto_20161229_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='donations',
            field=models.IntegerField(default=0),
        ),
    ]
