# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-30 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0008_auto_20161229_1938'),
        ('charity', '0007_auto_20161230_1201'),
    ]

    operations = [
    ]
