# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-30 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0009_charity_donations'),
        ('charity', '0009_merge_20161230_1208'),
    ]

    operations = [
    ]
