# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal_serializer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalpayment',
            name='username',
            field=models.CharField(default='DEFAULT', max_length=100),
        ),
        migrations.AlterField(
            model_name='paypalpayment',
            name='business',
            field=models.CharField(default='DEFAULT', max_length=100),
        ),
    ]
