# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 14:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharityAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal', models.CharField(default='DEFAULT', max_length=100)),
                ('description', models.TextField(default='DEFAULT', max_length=1000)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('charity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='charity.Charity')),
            ],
        ),
        migrations.CreateModel(
            name='DonorAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
