# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 22:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20161027_2156'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Charity',
            new_name='CharityAccount',
        ),
    ]
