# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20161027_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='charityaccount',
            name='description',
            field=models.TextField(default='DEFAULT', max_length=1000),
        ),
    ]
