# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_charityaccount_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='charityaccount',
            name='paypal',
            field=models.CharField(default='DEFAULT', max_length=100),
        ),
    ]
