# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='DEFAULT', max_length=100)),
                ('charity', models.CharField(default='DEFAULT', max_length=100)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('amount', models.IntegerField(default=0, null=True)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('GBP', 'GB Sterling')], max_length=3)),
            ],
        ),
    ]
