# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 15:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='DEFAULT', max_length=100)),
                ('charity', models.CharField(default='DEFAULT', max_length=100)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('amount', models.IntegerField(default=0, null=True)),
                ('currency', models.CharField(choices=[('', 'DEFAULT'), ('USD', 'US Dollar'), ('GBP', 'GB Sterling')], max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='PaypalPayment',
        ),
    ]
