# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-28 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='account_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='charity_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
