# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20161110_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('GBP', 'GB Sterling')], max_length=3),
        ),
    ]
