# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-29 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20161228_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='charity',
            new_name='paypal',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='username',
        ),
    ]
