# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-03 19:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0007_charity_donations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0003_auto_20161229_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='charity_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='charity',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='charity.Charity'),
        ),
    ]
